### ISSUE TITLE
Security audit proposal for a smart contract

### ISSUE THREAD

**Issue by yuriy77k** [paradoxDAO/accounting#1]
Hello.
 
My name is Yuriy, I'm acting Head of Security Department in Callisto Network.
We provide free security audit for a ETC / ETH smart contracts.
 
If you would like to make free security audit for accounting smart contracts you may create new  issue in our GitHub: https://github.com/EthereumCommonwealth/Auditing/issues.
 
I will be happy to answer your questions.

**Comment by paskals** [comment]
@yuriy77k thanks for your offer, but that's not necessary at the moment
